version: '1'
services:
  api:
    build: .
    ports:
      - '3000:3000'
    environment:
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: welcome123
      POSTGRES_DB: products_db
      JWT_SECRET_KEY: cT!6B^9rW@q2nV7yXz8*RtPb3@QxLfW4zUuG9&1YhLsZj2VfMhD
    depends_on:
      - db

  db:
    image: postgres:14
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: welcome123
      POSTGRES_DB: products_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
